// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HtjhAxX1PekcEM5KT03e7HNhKNIHrbY',
    appId: '1:662317488999:web:cc2ba5f3dfd212bc24adc2',
    messagingSenderId: '662317488999',
    projectId: 'ict602-group-project-d8ade',
    authDomain: 'ict602-group-project-d8ade.firebaseapp.com',
    storageBucket: 'ict602-group-project-d8ade.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8TFTHUl0V9PktAOCf-mghZOeTguEf4Y',
    appId: '1:662317488999:android:f78dd51a351d09de24adc2',
    messagingSenderId: '662317488999',
    projectId: 'ict602-group-project-d8ade',
    storageBucket: 'ict602-group-project-d8ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPJjg_HCRdB3q40X4ubYwYh363INuhaVU',
    appId: '1:662317488999:ios:a02a321594f9be8024adc2',
    messagingSenderId: '662317488999',
    projectId: 'ict602-group-project-d8ade',
    storageBucket: 'ict602-group-project-d8ade.firebasestorage.app',
    iosBundleId: 'com.example.ict602GroupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPJjg_HCRdB3q40X4ubYwYh363INuhaVU',
    appId: '1:662317488999:ios:a02a321594f9be8024adc2',
    messagingSenderId: '662317488999',
    projectId: 'ict602-group-project-d8ade',
    storageBucket: 'ict602-group-project-d8ade.firebasestorage.app',
    iosBundleId: 'com.example.ict602GroupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3HtjhAxX1PekcEM5KT03e7HNhKNIHrbY',
    appId: '1:662317488999:web:bf11e8acdc04f0cb24adc2',
    messagingSenderId: '662317488999',
    projectId: 'ict602-group-project-d8ade',
    authDomain: 'ict602-group-project-d8ade.firebaseapp.com',
    storageBucket: 'ict602-group-project-d8ade.firebasestorage.app',
  );
}
